language: php
node_js:
  - node

before_install:
  - npm install -g npm@latest

install:
  - php prepare.php

script:
  - php test.php

after_script:
  - php report.php
  - php cleanup.php

before_install:
  - nvm install lts/*
  - npm install -g npm@latest
  - npm install -g grunt-cli
