sudo: false

language: php

branches:
  only:
    - master

install:
  - php prepare.php

script:
  - php test.php

after_script:
  - php report.php
  - php cleanup.php

before_install:
  - nvm install 12
  - npm install -g npm@latest
